import fs from 'fs';
import path from 'path';

const inputFile = 'src/example/full_example/RtnUnits.md';
const outputFile = 'src/example/full_example/OwnerUnits.sql';

function convert() {
  const filePath = path.resolve(process.cwd(), inputFile);
  let content;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch (err) {
    console.error("Error reading file:", err);
    return;
  }

  const lines = content.split('\n');
  const units = [];

  // Set for uniqueness check
  const unitIds = new Set();

  lines.forEach(line => {
    // Parse line: | 2000000 | กองทัพเรือ | ทร. |
    const match = line.match(/^\|\s*(\d{7})\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|/);
    if (match) {
      const unitId = match[1];
      const unitName = match[2].trim();
      const unitAbbr = match[3].trim(); // might be '-' or empty

      if (unitIds.has(unitId)) {
        console.warn(`Duplicate UnitID found: ${unitId}, skipping.`);
        return;
      }
      unitIds.add(unitId);

      // Determine Parent and Level
      let parentId = null;
      let level = 1;

      if (unitId === '2000000') {
        level = 1;
        parentId = null; // Root
      } else if (unitId.endsWith('0000')) {
        // Level 2: 2xx0000 (e.g., 2270000)
        // Parent is 2000000
        level = 2;
        parentId = '2000000';
      } else if (unitId.endsWith('000')) {
        // Level 3: 2xxx000 (e.g., 2271000, 2272000)
        // Parent is 2xx0000 (e.g., 2270000)
        level = 3;
        parentId = unitId.substring(0, 3) + '0000';
      } else if (unitId.endsWith('00')) {
        // Level 4: 2xxxx00 (e.g., 2272400)
        // Parent is 2xxx000 (e.g., 2272000)
        level = 4;
        parentId = unitId.substring(0, 4) + '000';
      } else {
        // Level 5: All other units (ending in 0 or digit), e.g., 2159510, 2159516
        // Parent is 2xxxx00 (e.g., 2159500)
        level = 5;
        parentId = unitId.substring(0, 5) + '00';
      }

      units.push({
        unit_id: unitId,
        unit_name: unitName.replace(/'/g, "''"), // Escape quotes
        unit_abbr: unitAbbr.replace(/'/g, "''"),
        parent_id: parentId,
        unit_level: level
      });
    }
  });

  console.log(`Parsed ${units.length} units.`);

  // Generate SQL
  const sqlHeader = `
-- Generated by scripts/convert_rtn_units.js
-- Total Units: ${units.length}
-- contains hierarchy info: parent_id, unit_level

CREATE TABLE IF NOT EXISTS OwnerUnits (
    unit_id VARCHAR(7) PRIMARY KEY,
    unit_name VARCHAR(255) NOT NULL,
    unit_abbr VARCHAR(100),
    parent_id VARCHAR(7),
    unit_level INT
);

DELETE FROM OwnerUnits; 
-- Optionally delete existing data to re-seed

INSERT INTO OwnerUnits (unit_id, unit_name, unit_abbr, parent_id, unit_level) VALUES
`;

  const valueLines = units.map(u => {
    const parentVal = u.parent_id ? `'${u.parent_id}'` : 'NULL';
    const abbrVal = u.unit_abbr === '-' ? 'NULL' : `'${u.unit_abbr}'`;
    return `('${u.unit_id}', '${u.unit_name}', ${abbrVal}, ${parentVal}, ${u.unit_level})`;
  });

  const sqlContent = sqlHeader + valueLines.join(',\n') + ';\n';

  fs.writeFileSync(path.resolve(process.cwd(), outputFile), sqlContent, 'utf8');
  console.log(`SQL file written to ${outputFile}`);
}

convert();
